# config.py

# Couleurs
BACKGROUND_COLOR = "#008cb3"
BUTTON_COLOR = "#004e73"
TEXT_COLOR = "white"
PROGRESS_BAR_COLOR = "#d1d1d1"
BUTTON_BG_COLOR = "#d1d1d1"

# Polices
POLICE = "Arial"
TITLE_FONT = (POLICE, 20, "bold")
BUTTON_FONT = (POLICE, 16)
LABEL_FONT = (POLICE, 16)
PROGRESS_LABEL_FONT = (POLICE, 12)
FOOTER_FONT = (POLICE, 10, "bold")
ENTRY_FONT = ("Arial", 12)
RADIO_BUTTON_FONT = ("Arial", 10)

# Tailles
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 400
PROGRESS_BAR_LENGTH = 100
